version: "2"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  django:
    build: .
    command: ./jenkins/wait-for-it.sh db:5432 -- ./manage.py test --verbosity=2
    links:
      - db
    volumes:
      - ./reports:/app/reports
    environment:
      DJANGO_SECRET_KEY: unit-tests
      DJANGO_SETTINGS_MODULE: data-hub-api.settings.jenkins
      DB_NAME: data-hub-api
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
